databases:
  - name: team-manager-db
    plan: free

services:
  - type: web
    name: team-manager
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: team-manager-db
          property: connectionString
